export const ON_TEXTAREA_CHANGE_HANDLER = 'ON_TEXTAREA_CHANGE_HANDLER';
export const ON_INPUT_CHANGE_HANDLER = 'ON_INPUT_CHANGE_HANDLER';
export const ON_CLICK_BTN_HANDLER = 'ON_CLICK_BTN_HANDLER';
export const RESET_FORM = 'RESET_FORM';
export const ON_DELETE = 'ON_DELETE';
export const FETCH_LOCAL_STORAGE = 'FETCH_LOCAL_STORAGE';